spring.application.name=inventory-service
server.port=8082
spring.cloud.discovery.enabled=false



# database configuration ----

# URL de connexion à la base H2 (en mémoire)
spring.datasource.url=jdbc:h2:mem:inventroy-service

# Pilote JDBC
spring.datasource.driver-class-name=org.h2.Driver

# Identifiants par défaut
spring.datasource.username=sa
spring.datasource.password=

# Activation de la console H2 dans le navigateur
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Gestion automatique du schéma JPA/Hibernate (optionnel)
spring.jpa.hibernate.ddl-auto=update
